backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.30;
shadow-offset-x = -6;
shadow-offset-y = -6;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

corner-radius = 8;

blur:
{
    method = "dual_kawase";
    strength = 3;
};

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

inactive-opacity = 1.0;
active-opacity = 1.0;
